Major v3.0 Release
Major new release of software and firmware: v3.0.26

* No longer requires root access to run Python menu (now in menu.py)
* Control software runs outside of docker "python3 menu.py --help" 
* Streamlined firmware supporting arbitrary strings for OLED
* Camera view streamed to http://moab.local (only when plate is active)
* Ball colors besides orange work
* BOT INFO menu shows DHCP-assigned IP address to help ssh
* No longer restricted to three brains
* Custom brain names will show in the menu
* Graceful menu and firmware restarts if either crashes
* New `bot` CLI command to control and query Moab

Follow instructions at https://github.com/microsoft/moabian/wiki/Upgrade-from-2.4.1-to-3.0 to upgrade.

Co-authored-by: Scott Stanfield <scott@stanfield.io>
Co-authored-by: Kirill Polzounov <kirill.polzounov@ucalgary.ca>
Co-authored-by: polzounov <9689620+polzounov@users.noreply.github.com>
Co-authored-by: John Alexander (MSFT) <john.alexander@microsoft.com>
Co-authored-by: Scott Stanfield <scott@stanfield.io>
Co-authored-by: Denise Feirstein <denise.feirstein@microsoft.com>

diff --git a/os/files/home/bashrc b/os/files/home/bashrc
--- a/os/files/home/bashrc
+++ b/os/files/home/bashrc
@@ -1,20 +1,19 @@
 export CLICOLOR=1
 export LANG="en_US.UTF-8"
 export GOPATH=$HOME/.go
-export PATH=$HOME/.local/bin:$PATH:/usr/local/go/bin:$GOPATH/bin:.
+export PATH=$HOME/.local/bin:$PATH:$HOME/moab/bin:/usr/local/go/bin:$GOPATH/bin:.
 
 export LESS="--quit-if-one-screen --no-init --ignore-case  --RAW-CONTROL-CHARS --quiet --dumb --LONG-PROMPT"
 export EDITOR="vim"
 export BLOCK_SIZE="'1"  # add commas to file size listings
 
-# Don't process the rest of the file for non-interactive shells
-# as indicated by a PS1 prompt
-[ -z "$PS1" ] && return
-
 # Moab specific
 alias logs="docker logs control -f"
 alias t="tmux -2 new-session -A -s moabian"
 alias dc="docker-compose"
+alias fwlog="sudo minicom --device=/dev/ttyAMA0"
+alias fwshell="sudo minicom --device=/dev/ttyAMA1"
+alias ports="sudo netstat -atlp"
 
 # General aliases
 lsflags="--color=auto --group-directories-first -F "
@@ -27,26 +26,32 @@ alias lls="ls ${lsflags} -l --sort=size --reverse"       # sort by date
 alias lle="ls ${lsflags} -l --sort=extension "           # sort by extension
 
 alias ,="cd .."
-alias m="less"
-alias h='history'
-alias hg="history | grep -i"
-alias @="printenv | grep -i"
-
+alias ga='git add'
+alias gb='git branch'
+alias gc='git commit -m'
+alias gco="git checkout"
 alias gd='git diff'
-alias cp='cp --archive'
-alias df='df --human-readable'
-alias pd='pushd'
-alias gs="git status"
-alias gd="git diff"
-alias vi="vim -o"
+alias gf='git fetch'
+alias gk='git checkout'
+alias gp='git pull'
+alias gpush='git push'
+alias gs='git status'
+
+alias hg="history | grep -i"
+alias h='history'
+alias m="less"
 alias path='echo $PATH | tr : "\n" | cat -n'
+alias p="python3"
+alias @="printenv | grep -i"
 alias rg="rg --pretty --smart-case"
+alias vi="vim -o"
+alias vim="vim -o"
 
 shopt -s checkwinsize                       # reset lines & cols after resize
 shopt -s histappend                         # append rather than overwrite history
-export HISTCONTROL=ignoreboth
 export HISTSIZE=1000                        # save last 100k commands
 export HISTFILESIZE=1000                    # save last 100k commands
+export HISTCONTROL=ignoreboth
 
 # auto cd to a folder by typing it's name
 shopt -s autocd
@@ -58,4 +63,75 @@ function cd {
 
 if [ -x /usr/bin/dircolors ]; then
     test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
+fi
+
+
+# Set prompt and title (for interactive shells only)
+if [ "$(expr $- : '.*i')" -ne 0 ]; then
+
+  # this works for sh and bash
+  if [ -z "$ZSH_VERSION" ]; then
+      # first get exit code of last command, and set colors
+      PS1="\$(\
+      EXIT=\"\$?\" ; \
+      BLUE=\"\[\e[38;5;39m\]\" ; \
+      RED=\"\[\e[31m\]\" ; \
+      ORANGE=\"\[\e[38;5;208m\]\" ; \
+      WHITE=\"\[\e[0m\]\" ; "
+      # endchar
+      #   use # for root and $ for non-root users
+      #   use white for default color, and red if last exit code is non-zero
+      # username
+      #   use red for root blue(39) for non-root users
+      PS1+="\
+      endchar=\"\\$\${WHITE}\" ; \
+      username=\"\${BLUE}\u\${WHITE}\" ; \
+      if [ \"\$UID\" = \"0\" ]; then
+          username=\"\${RED}\u\${WHITE}\" ; \
+      fi ; \
+      if [ \"\$EXIT\" -eq 0 ]; then
+          endchar=\"\${WHITE}\$endchar\" ; \
+      else \
+          endchar=\"\${RED}\$endchar\"
+      fi ; "
+      # hostname in orange
+      PS1+="\
+      host=\"\${ORANGE}\H\${WHITE}\" ; "
+      # current directory in blue(39)
+      PS1+="\
+      dir=\"\${BLUE}\w\${WHITE}\" ; "
+      # set prompt, and additionally set window title for xterm
+      if [ "${TERM:0:5}" = "xterm" ]; then
+          PS1+="echo \"\[\e]2;\u@\H :: \w\a\]\${username}@\${host}\${dir} \${endchar} \" )"
+      else
+          PS1+="echo \"\${username}@\${host} \${dir} \${endchar} \" )"
+      fi
+
+  else
+    # this works for zsh
+      # endchar
+      # use red if last command has non-zero exit
+      # use # for root and $ for non-root users
+      local _root_endch="%(?.#.%F{red}#%f)"
+      local _other_endch="%(?.$.%F{red}$%f)"
+      local _endchar="%(#.${_root_endch}.${_other_endch})"
+      # use red for root and blue(39) for non-root users
+      local _username="%F{%(#.red.39)}%n%f"
+      # hostname in orange
+      local _host="%F{208}%m%f"
+      # current directory in blue(39)
+      local _dir="%F{39}%~%f"
+      # set prompt
+      PS1="${_username}@${_host} ${_dir} ${_endchar} "
+      # additionally set window title for xterm
+      __stateless_title () {    # for xterm, set window title
+        if [ "${TERM:0:5}" = "xterm" ]; then
+            print -Pn "\e]2;%n\@%m :: %~\a"
+        fi
+      }
+      __stateless_title
+      autoload -Uz add-zsh-hook
+      add-zsh-hook chpwd __stateless_title
+  fi
+  export PS1
 fi
